"""
Contains big constants used in the tests.
"""

HELPER_EXPECTED_MESSAGE = ('Commands                                         Information\n'
                           '-----------------------------------------------  '
                           '-----------------------------------------------------------------------'
                           '----------------------------------------------------\n'
                           'help                                             '
                           'This command prints out '
                           'this information.\n'
                           'stop                                             '
                           'This command stops the '
                           'execution of the problem.\n'
                           'clear                                            '
                           'This command clears the '
                           'console.\n'
                           'gen [<password_length>]                          '
                           'This command generates a '
                           'random password. If do not set the length of the '
                           'password, by default it '
                           'will be 8.\n'
                           '                                                 '
                           '<password_length> must be a '
                           'positive integer.\n'
                           'login                                            '
                           'This command shows the '
                           'login prompt.\n'
                           'signup                                           '
                           'This commands shows the '
                           'signup prompt.\n'
                           'account [-o <org_name>] add                      '
                           'This command creates a new '
                           'account.\n'
                           'account [-o <org_name>] edit <account_name>      '
                           'This command updates the '
                           'information of the account. When editing a field, '
                           'set it to "-del" in order '
                           'to make it empty.\n'
                           '                                                 '
                           'You cannot delete the '
                           'password with "-del".\n'
                           'account [-o <org_name>] -rm <account_name>       '
                           'This command deletes the '
                           'account.\n'
                           'account [-o <org_name>] url <account_name>       '
                           'This command opens the '
                           'login page of the account if the account has a valid url.\n'
                           'account [-o <org_name>] view -all                '
                           'This command shows the '
                           'non-sensitive information of all accounts who are owned by the current '
                           'owner(user/org).\n'
                           'account [-o <org_name>] view <account_name>      '
                           'This command shows the '
                           'non-sensitive information of the account.\n'
                           'account [-o <org_name>] view-by-app <app_name>   '
                           'This command shows the '
                           'non-sensitive information of all accounts by app name who are owned by '
                           'thecurrent owner(user/org).\n'
                           'account [-o <org_name>] copy-pwd <account_name>  '
                           'This command copies the '
                           'password of the account to your clipboard.\n'
                           'account [-o <org_name>] pwd <account_name>       '
                           'This command shows the '
                           'password of the account on the console.\n'
                           '                                                 '
                           'Please enter "clear" after '
                           'that in order the password to be removed from the console.\n'
                           'account [-o <org_name>] cat <org_name>           '
                           'This command shows the '
                           'non-sensitive information of all accounts\n'
                           '                                                 '
                           'who are owned by the '
                           'current user and are from this category.\n'
                           'category [-o <org_name>] -all                    '
                           'This command shows all '
                           'categories who are owned by the current user.\n'
                           'category [-o <org_name>] -rm <category_name      '
                           'This command deletes the '
                           'category and for every account from the category '
                           'the category property is '
                           'set to empty.\n'
                           '"shortcut info"                                  '
                           'If you use "-last" instead '
                           'of <account_name>/<org_name> the programme will '
                           'use the most recently used '
                           'account/organization\n'
                           '                                                 '
                           'if this is not the first '
                           'operation with account/organization for the session.\n'
                           '                                                 '
                           '"-last" for organization '
                           'can be used only on account commands(not when '
                           'modifying the organization)\n'
                           '                                                  '
                           '-o <org_name> allows the '
                           'user to view, create,update and delete accounts '
                           'and categories from an '
                           'organization.\n'
                           'org all                                          '
                           'This command prints the '
                           'names of all the organizations you are a member of.\n'
                           'org create [<users>]                             '
                           'This command creates an '
                           'organization with members [<users>](the names of '
                           'valid users) and the owner is you.\n'
                           'org delete <org_name>                            '
                           'This command deletes an '
                           'organization with name org_name.\n'
                           'org add <org_name> <username>                    '
                           'This command adds user with '
                           'username <username> to the organization <org_name>.\n'
                           'org remove <org_name> <username>                 '
                           'This command removes user '
                           'with username <username> from the organization <org_name>.\n'
                           'org view <org_name>                              '
                           'This command visualizes the '
                           'non-sensitive information of the organization.\n')
