name: pmenv
#channels:
#- defaults
#- conda-forge
dependencies:
  - python=3.9
  - tabulate
  - validators
  - pylint
  - pip
  - pip:
    - google-cloud-datastore
    - pyperclip
    - password-strength