name: pmenv
#channels:
#- defaults
#- conda-forge
dependencies:
  - python=3.9
  - tabulate
  - validators
  - pylint
  - pynacl
  - bcrypt
  - pycryptodome
  - pytest
  - pytest-mock
  - coverage
  - pyreadline3
#  - libsodium
  - pip
  - pip:
    - google-cloud-datastore
    - pyperclip
    - password-strength
    - random-password-generator
#    - scrypt
#    - pysodium