name: pmenv
#channels:
#- defaults
#- conda-forge
dependencies:
  - python=3.9
  - tabulate
  - validators
  - pylint
  - pynacl
  - bcrypt
  - pycryptodome
#  - libsodium
  - pip
  - pip:
    - google-cloud-datastore
    - pyperclip
    - password-strength
#    - scrypt
#    - pysodium