#!/bin/sh
'''exec' E:/FMI/4 year/7 term/Python/project/password_manager/envs/pmenv/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys
from isort.main import identify_imports_main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(identify_imports_main())
